spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/auth_service?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: '{cipher}b03f74a3e1c8e958180eb2381c047a717e58d4e35b315d0e0985aa8c1dec7ad4' # 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}
    consumer:
      group-id: auth-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      max-poll-records: 10
      properties:
        # 역직렬화할 때 신뢰할 패키지 지정
        spring.json.trusted.packages: "com.example.*"
        spring.json.type.mapping: >
          UserRegisteredEvent:com.example.authservice.domain.event.UserRegisteredEvent
    producer: # (DLQ 전송용)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        enable.idempotence: true

jwt:
  secret: '{cipher}2eba26d81a4d9e57d60be1c695dc7b6c27a0df6303a57450de2da92ba104d1b25ec0faa562d434c8c891926087b491d9e5caffaa0b80b73305a27b81ecef14e7037c44a7e7ecec85f3872e1c2ab50cef'
  access-token:
    expiration: 1800000
  refresh-token:
    expiration: 604800000

springwolf:
  docket:
    base-package: com.example.authservice.consumer

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect