spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      
  elasticsearch:
    uris: ${ELASTICSEARCH_HOST:localhost}:9200

springwolf:
  docket:
    base-package: com.example.catalogservice.consumer

product-service:
  url: ""