spring:
  data:
    elasticsearch:
      client:
        endpoints: ${ELASTICSEARCH_HOST:localhost}:9200
        
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

springwolf:
  docket:
    base-package: com.example.catalogservice.consumer

product-service:
  url: ""