spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Auth Service Routes - USER-level endpoints (관리자 로그인도 같은 route 사용)
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
              filters:
                - RewritePath=/api/(?<segment>.*), /api/$\{segment}
                - name: CircuitBreaker
                  args:
                    name: authServiceCircuitBreaker
                    fallbackUri: forward:/fallback/auth
    
            # User Service Routes - USER-level endpoints
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - RewritePath=/api/(?<segment>.*), /api/$\{segment}
                - name: JwtAuthentication
                  args:
                    requiredRole: USER
                    whitelist:
                      - /api/users/signup
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/user

            # User Service Routes - ADMIN-level endpoints
            - id: admin-user-service
              uri: lb://user-service
              predicates:
                - Path=/api/admin/users/**
              filters:
                - RewritePath=/api/(?<segment>.*), /api/$\{segment}
                - name: JwtAuthentication
                  args:
                    requiredRole: ADMIN
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/user

            # Product Service Routes - File resource
            - id: product-service-files
              uri: lb://product-service
              predicates:
                - Path=/product/files/**
              filters:
                - RewritePath=/product/files/(?<segment>.*), /files/${segment}

            # Product Service Routes - ADMIN-level endpoints
            - id: admin-product-service
              uri: lb://product-service
              predicates:
                - Path=/api/admin/products/**,/api/admin/categories/**
              filters:
                - RewritePath=/api/(?<segment>.*), /api/$\{segment}
                - name: JwtAuthentication
                  args:
                    requiredRole: ADMIN
                - name: CircuitBreaker
                  args:
                    name: productServiceCircuitBreaker
                    fallbackUri: forward:/fallback/product

            # Catalog Service Routes - USER-level endpoints
            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/api/catalog/**
              filters:
                - RewritePath=/api/(?<segment>.*), /api/$\{segment}
                - name: CircuitBreaker
                  args:
                    name: catalogServiceCircuitBreaker
                    fallbackUri: forward:/fallback/catalog

            # Order Service Routes - USER-level endpoints
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - RewritePath=/api/(?<segment>.*), /api/$\{segment}
                - name: JwtAuthentication
                  args:
                    requiredRole: USER
                - name: CircuitBreaker
                  args:
                    name: orderServiceCircuitBreaker
                    fallbackUri: forward:/fallback/order

            # Order Service Routes - ADMIN-level endpoints
            - id: admin-order-service
              uri: lb://order-service
              predicates:
                - Path=/api/admin/orders/**
              filters:
                - RewritePath=/api/(?<segment>.*), /api/$\{segment}
                - name: JwtAuthentication
                  args:
                    requiredRole: ADMIN
                - name: CircuitBreaker
                  args:
                    name: orderServiceCircuitBreaker
                    fallbackUri: forward:/fallback/order

            # Payment Service Routes - USER-level endpoints
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**
              filters:
                - RewritePath=/api/(?<segment>.*), /api/$\{segment}
                - name: JwtAuthentication
                  args:
                    requiredRole: USER
                - name: CircuitBreaker
                  args:
                    name: paymentServiceCircuitBreaker
                    fallbackUri: forward:/fallback/payment


          # Global CORS Configuration
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: false


jwt:
  secret: '{cipher}2eba26d81a4d9e57d60be1c695dc7b6c27a0df6303a57450de2da92ba104d1b25ec0faa562d434c8c891926087b491d9e5caffaa0b80b73305a27b81ecef14e7037c44a7e7ecec85f3872e1c2ab50cef'


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 3s
        registerHealthIndicator: true
    instances:
      authServiceCircuitBreaker:
        baseConfig: default
      userServiceCircuitBreaker:
        baseConfig: default
      productServiceCircuitBreaker:
        baseConfig: default
      catalogServiceCircuitBreaker:
        baseConfig: default
      orderServiceCircuitBreaker:
        baseConfig: default
      paymentServiceCircuitBreaker:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
    instances:
      authServiceCircuitBreaker:
        baseConfig: default
      userServiceCircuitBreaker:
        baseConfig: default
      productServiceCircuitBreaker:
        baseConfig: default
      catalogServiceCircuitBreaker:
        baseConfig: default
      orderServiceCircuitBreaker:
        baseConfig: default
      paymentServiceCircuitBreaker:
        baseConfig: default


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, refresh, metrics, circuitbreakers