spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/order_service?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: '{cipher}b03f74a3e1c8e958180eb2381c047a717e58d4e35b315d0e0985aa8c1dec7ad4'
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        enable.idempotence: true
        spring.json.type.mapping: >
          orderCreatedEvent:com.example.orderservice.domain.event.OrderCreatedEvent

springwolf:
  docket:
    base-package: com.example.orderservice.global.service
  plugin:
    kafka:
      publishing:
        enabled: true
        producer:
          bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            acks: all
            enable.idempotence: true
            spring.json.type.mapping: >
              orderCreatedEvent:com.example.orderservice.domain.event.OrderCreatedEvent


product-service:
  url: ""