logging:
  level:
    com.example.orderservice.global.service.outbox.OutboxEventScheduler: WARN

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/order_service?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: '{cipher}b03f74a3e1c8e958180eb2381c047a717e58d4e35b315d0e0985aa8c1dec7ad4'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      max-poll-records: 10
      properties:
        # 역직렬화할 때 신뢰할 패키지 지정
        spring.json.trusted.packages: "com.example.*"
        spring.json.type.mapping: >
          paymentConfirmedEvent:com.example.orderservice.consumer.event.PaymentConfirmedEvent,
          paymentCancelledEvent:com.example.orderservice.consumer.event.PaymentCancelledEvent,
          shippingStartedEvent:com.example.orderservice.consumer.event.ShippingStartedEvent,
          shippingDeliveredEvent:com.example.orderservice.consumer.event.ShippingDeliveredEvent,
          returnCompletedEvent:com.example.orderservice.consumer.event.ReturnCompletedEvent
    
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        enable.idempotence: true
        spring.json.type.mapping: >
          orderCreatedEvent:com.example.orderservice.domain.event.OrderCreatedEvent,
          orderCancelledEvent:com.example.orderservice.domain.event.OrderCancelledEvent,
          couponUsedEvent:com.example.orderservice.domain.event.CouponUsedEvent,
          couponRestoredEvent:com.example.orderservice.domain.event.CouponRestoredEvent

springwolf:
  docket:
    base-package: com.example.orderservice.global.service
  plugin:
    kafka:
      publishing:
        enabled: true
        producer:
          bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            acks: all
            enable.idempotence: true
            spring.json.type.mapping: >
              orderCreatedEvent:com.example.orderservice.domain.event.OrderCreatedEvent,
              orderCancelledEvent:com.example.orderservice.domain.event.OrderCancelledEvent,
              couponUsedEvent:com.example.orderservice.domain.event.CouponUsedEvent,
              couponRestoredEvent:com.example.orderservice.domain.event.CouponRestoredEvent


product-service:
  url: ""

payment-service:
  url: ""

promotion-service:
  url: ""

shipping-service:
  url: ""