logging:
  level:
    com.example.shippingservice.global.service.outbox.OutboxEventScheduler: WARN

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shipping_service?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: '{cipher}b03f74a3e1c8e958180eb2381c047a717e58d4e35b315d0e0985aa8c1dec7ad4'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}
    consumer:
      group-id: shipping-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      max-poll-records: 10
      properties:
        # 역직렬화할 때 신뢰할 패키지 지정
        spring.json.trusted.packages: "com.example.*"
        spring.json.type.mapping: >
          orderCreatedEvent:com.example.shippingservice.consumer.event.OrderCreatedEvent,
          orderCancelledEvent:com.example.shippingservice.consumer.event.OrderCancelledEvent
    
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        enable.idempotence: true
        spring.json.type.mapping: >
          shippingStartedEvent:com.example.shippingservice.domain.event.ShippingStartedEvent,
          shippingDeliveredEvent:com.example.shippingservice.domain.event.ShippingDeliveredEvent,
          returnApprovedEvent:com.example.shippingservice.domain.event.ReturnApprovedEvent,
          returnInTransitEvent:com.example.shippingservice.domain.event.ReturnInTransitEvent,
          returnCompletedEvent:com.example.shippingservice.domain.event.ReturnCompletedEvent,
          exchangeApprovedEvent:com.example.shippingservice.domain.event.ExchangeApprovedEvent,
          exchangeCollectingEvent:com.example.shippingservice.domain.event.ExchangeCollectingEvent,
          exchangeReturnCompletedEvent:com.example.shippingservice.domain.event.ExchangeReturnCompletedEvent,
          exchangeShippingEvent:com.example.shippingservice.domain.event.ExchangeShippingEvent,
          exchangeCompletedEvent:com.example.shippingservice.domain.event.ExchangeCompletedEvent


springwolf:
  docket:
    base-package: com.example.orderservice.global.service
  plugin:
    kafka:
      publishing:
        enabled: true
        producer:
          bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            acks: all
            enable.idempotence: true
            spring.json.type.mapping: >
              shippingStartedEvent:com.example.shippingservice.domain.event.ShippingStartedEvent,
              shippingDeliveredEvent:com.example.shippingservice.domain.event.ShippingDeliveredEvent,
              returnApprovedEvent:com.example.shippingservice.domain.event.ReturnApprovedEvent,
              returnInTransitEvent:com.example.shippingservice.domain.event.ReturnInTransitEvent,
              returnCompletedEvent:com.example.shippingservice.domain.event.ReturnCompletedEvent,
              exchangeApprovedEvent:com.example.shippingservice.domain.event.ExchangeApprovedEvent,
              exchangeCollectingEvent:com.example.shippingservice.domain.event.ExchangeCollectingEvent,
              exchangeReturnCompletedEvent:com.example.shippingservice.domain.event.ExchangeReturnCompletedEvent,
              exchangeShippingEvent:com.example.shippingservice.domain.event.ExchangeShippingEvent,
              exchangeCompletedEvent:com.example.shippingservice.domain.event.ExchangeCompletedEvent


order-service:
  url: ""

mock-delivery-server:
  url: "http://mock-delivery:8080"
  courier-account-key: CJ_COURIER_ACCOUNT_KEY_2024
  tracking-api-key: SMART_DELIVERY_API_KEY_2024
  courier-code: "04"


shipping:
  tracking:
    poll-interval-ms: 1000